name = "TestItemDetection"
uuid = "76b0de8b-5c4b-48ef-a724-914b33ca988d"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "0.1.0-DEV"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"

[compat]
julia = "1"
CSTParser = "3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
